version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"          # root of repo
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"